{
    'name': 'Sale Report Extended',
    'version': '1.0',
    'category': 'Sales Management',    
    'complexity': "easy",
    'description': "",
    'author': 'Emipro Technologies',
    'website': 'http://www.emiprotechnologies.com',    
    'depends': ['product_stone_search_ept','report_aeroo_ooo'],
    'init_xml': [],
    'update_xml': ['view/sale_report.xml',                   
                   'view/sale_shop.xml',
                   'view/invoice_view.xml',
                   'view/invoice_report.xml',
		   'view/sale_order_aeroo_report_view.xml',
                   ],        
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'certificate': '',
}
